micronaut:
  application:
    name: revolut-home-task
datasources:
  default:
    url: jdbc:h2:mem:default
    username: "sa"
    password: ""
    driverClassName: org.h2.Driver
flyway:
  datasources:
    default:
      schemas: PUBLIC
      locations: classpath:migrations
