DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS CURRENCIES;

CREATE TABLE CURRENCIES
(
    ID        VARCHAR(3) PRIMARY KEY NOT NULL,
    FULL_NAME VARCHAR(45)
);

CREATE TABLE PUBLIC.ACCOUNTS
(
    ID       IDENTITY PRIMARY KEY NOT NULL,
    CURRENCY VARCHAR(3)           NOT NULL,
    BALANCE  DECIMAL              NOT NULL,
    CREATED  TIMESTAMP            NOT NULL,
    FOREIGN KEY (CURRENCY) REFERENCES CURRENCIES (ID)
);

CREATE TABLE PUBLIC.TRANSACTIONS
(
    ID        IDENTITY PRIMARY KEY,
    SENDER    BIGINT  NOT NULL,
    RECIPIENT BIGINT  NOT NULL,
    AMOUNT    DECIMAL NOT NULL,
    SENT      TIMESTAMP,
    FOREIGN KEY (SENDER) REFERENCES ACCOUNTS (ID),
    FOREIGN KEY (RECIPIENT) REFERENCES ACCOUNTS (ID),
    CHECK (AMOUNT > 0)
);